# Generated by Django 3.0.7 on 2020-06-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='head_title',
            field=models.CharField(default='', max_length=220),
            preserve_default=False,
        ),
    ]
